app <- ShinyDriver$new("../")
app$snapshotInit("mytest")

app$snapshot()
app$setInputs(dynamic = 17)
app$snapshot()
app$setInputs(input_type = "checkbox")
app$snapshot()
app$setInputs(dynamic = FALSE)
app$snapshot()
app$setInputs(input_type = "selectInput")
app$snapshot()
app$setInputs(dynamic = "option1")
app$snapshot()
