on:
  push:
    branches: [main, master, rc-**]
  pull_request:
    branches: [main, master]

name: pkgdown

jobs:
  pkgdown:
    runs-on: ubuntu-20.04
    env:
      R_KEEP_PKG_SOURCE: yes
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-pandoc@v1
      - uses: r-lib/actions/setup-r@v1
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v1
        with:
          extra-packages: |
            pkgdown
            testthat

      - name: Install package
        run: R CMD INSTALL .

      - name: Build Site (PR)
        if: github.event_name != 'push'
        shell: Rscript {0}
        run: |
          pkgdown::build_site(new_process = FALSE)
          # Must validate after building site
          testthat::expect_warning({
            pkgdown::build_reference_index()
          }, NA)

      - name: Build and deploy pkgdown site (push)
        if: github.event_name == 'push'
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          Rscript -e 'pkgdown::deploy_to_branch(new_process = FALSE)'
