on:
  push:
    branches: [main, rc-**]
  pull_request:
    branches: [main]
  schedule:
    - cron:  '0 8 * * 1' # every monday

name: Package checks

jobs:
  website:
    uses: rstudio/shinycoreci/.github/workflows/call-website.yaml@v1
    with:
      pandoc-version: '2.9.2.1'
  routine:
    uses: rstudio/shinycoreci/.github/workflows/call-routine.yaml@v1
    with:
      pandoc-version: '2.9.2.1'
  R-CMD-check:
    uses: rstudio/shinycoreci/.github/workflows/call-R-CMD-check.yaml@v1
    with:
      pandoc-version: '2.9.2.1'


## Would be nice to use this for caching phantomjs installation
# - name: Install shinytest (so that phantomJS can be installed)
#   shell: Rscript {0}
#   run: |
#     pak::local_install(".")
# - name: Find PhantomJS path
#   id: phantomjs
#   run: |
#     echo "::set-output name=path::$(Rscript -e 'cat(shinytest:::phantom_paths()[[1]])')"
# - name: Cache PhantomJS
#   uses: actions/cache@v2
#   with:
#     path: ${{ steps.phantomjs.outputs.path }}
#     key: ${{ matrix.config.os }}-phantomjs
#     restore-keys: ${{ matrix.config.os }}-phantomjs
# - name: Install PhantomJS
#   shell: Rscript {0}
#   run: |
#     options(install.packages.check.source = 'no')
#     if (!shinytest::dependenciesInstalled()) shinytest::installDependencies()
